# Generated by Django 4.1.3 on 2022-12-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_feature_category_parent_category_id_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
