# Generated by Django 4.1.3 on 2022-12-03 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_alter_product_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='units',
        ),
    ]
